---
- name: Install Docker, Pull image and run the container
  hosts: web_servers
  become: yes

  collections:
    - community.docker

  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  # - name: Install Java 21
  #   apt:
  #     name: openjdk-21-jdk
  #     state: present

  - name: Ensure Docker is installed
    ansible.builtin.package:
      name: docker-ce
      state: present

  - name: Pull Docker image
    community.docker.docker_image:
      name: monayem02/host-name-app
      source: pull
  
  - name: Run Docker container
    community.docker.docker_container:
      name: host-name-app
      image: monayem02/host-name-app
      state: started
      published_ports:
        - "8080:8080"
      env:
        HOST_HOSTNAME: "{{ ansible_hostname }}"
    